let results = {
    results: [
    {
      id: 1011334,
      name: '3-D Man',
      description: '',
      modified: '2014-04-29T14:18:17-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011334',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1017100,
      name: 'A-Bomb (HAS)',
      description: "Rick Jones has been Hulk's best bud since day one, but now he's more than a friend...he's a teammate! Transformed by a Gamma energy explosion, A-Bomb's thick, armored skin is just as strong and powerful as it is blue. And when he curls into action, he uses it like a giant bowling ball of destruction! ",
      modified: '2013-09-18T15:54:04-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1017100',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009144,
      name: 'A.I.M.',
      description: 'AIM is a terrorist organization bent on destroying the world.',
      modified: '2013-10-17T14:41:30-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009144',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010699,
      name: 'Aaron Stack',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010699',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009146,
      name: 'Abomination (Emil Blonsky)',
      description: 'Formerly known as Emil Blonsky, a spy of Soviet Yugoslavian origin working for the KGB, the Abomination gained his powers after receiving a dose of gamma radiation similar to that which transformed Bruce Banner into the incredible Hulk.',
      modified: '2012-03-20T12:32:12-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009146',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1016823,
      name: 'Abomination (Ultimate)',
      description: '',
      modified: '2012-07-10T19:11:52-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1016823',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009148,
      name: 'Absorbing Man',
      description: '',
      modified: '2013-10-24T14:32:08-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009148',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009149,
      name: 'Abyss',
      description: '',
      modified: '2014-04-29T14:10:43-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009149',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010903,
      name: 'Abyss (Age of Apocalypse)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010903',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011266,
      name: 'Adam Destine',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011266',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010354,
      name: 'Adam Warlock',
      description: 'Adam Warlock is an artificially created human who was born in a cocoon at a scientific complex called The Beehive.',
      modified: '2013-08-07T13:49:06-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010354',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010846,
      name: 'Aegis (Trey Rollins)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010846',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1017851,
      name: 'Aero (Aero)',
      description: '',
      modified: '2021-08-27T17:52:34-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1017851',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1012717,
      name: 'Agatha Harkness',
      description: '',
      modified: '2021-08-06T11:30:56-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1012717',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011297,
      name: 'Agent Brand',
      description: '',
      modified: '2013-10-24T13:09:30-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011297',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011031,
      name: 'Agent X (Nijo)',
      description: "Originally a partner of the mind-altering assassin Black Swan, Nijo spied on Deadpool as part of the Swan's plan to exact revenge for Deadpool falsely taking credit for the Swan's assassination of the Four Winds crime family, which included Nijo's brother.",
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011031',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009150,
      name: 'Agent Zero',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009150',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011198,
      name: 'Agents of Atlas',
      description: '',
      modified: '2016-02-03T10:25:22-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011198',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011175,
      name: 'Aginar',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011175',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011136,
      name: 'Air-Walker (Gabriel Lan)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011136',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011176,
      name: 'Ajak',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011176',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010870,
      name: 'Ajaxis',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010870',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011194,
      name: 'Akemi',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011194',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011170,
      name: 'Alain',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011170',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009240,
      name: 'Albert Cleary',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009240',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011120,
      name: 'Albion',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011120',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010836,
      name: 'Alex Power',
      description: '',
      modified: '2011-10-27T09:57:58-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010836',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010755,
      name: 'Alex Wilder',
      description: 'Despite being the only one of the Runaways without any superhuman abilities or tech, Alex Wilder became the de facto leader of the group due to his natural leadership skills and intellect, as well as prodigy-level logic and strategy.',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010755',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011214,
      name: 'Alexa Mendez',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011214',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009497,
      name: 'Alexander Pierce',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009497',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1014990,
      name: 'Alice',
      description: '',
      modified: '2010-11-18T16:01:44-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1014990',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009435,
      name: 'Alicia Masters',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009435',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010370,
      name: 'Alpha Flight',
      description: '',
      modified: '2013-10-24T13:09:22-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010370',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011324,
      name: 'Alpha Flight (Ultimate)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011324',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011164,
      name: 'Alvin Maker',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011164',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011227,
      name: 'Amadeus Cho',
      description: '',
      modified: '2013-08-07T13:50:56-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011227',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009567,
      name: 'Amanda Sefton',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009567',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011382,
      name: 'Amazoness',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011382',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011361,
      name: 'American Eagle (Jason Strongbow)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011361',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009151,
      name: 'Amiko',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009151',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010672,
      name: 'Amora',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010672',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010673,
      name: 'Amphibian (Earth-712)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010673',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010905,
      name: 'Amun',
      description: "Amun is a ruthless teenage assassin, employed by the Sisterhood of the Wasp to serve under the mage Vincent after Araña interrupted the ritual to initiate the Wasp's new chosen one.",
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010905',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009152,
      name: 'Ancient One',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009152',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1016824,
      name: 'Ancient One (Ultimate)',
      description: '',
      modified: '2012-07-10T19:15:49-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1016824',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011684,
      name: 'Angel (Angel Salvadore)',
      description: 'Driven out of home by her abusive step-father, fourteen-year old Angel Salvadore slept in the woods, where her mutant nature manifested itself in the form of a protective cocoon.',
      modified: '2021-08-19T00:06:46-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011684',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011396,
      name: 'Angel (Thomas Halloway)',
      description: '',
      modified: '2014-03-05T13:14:48-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011396',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011338,
      name: 'Angel (Ultimate)',
      description: '',
      modified: '2014-03-05T13:15:49-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011338',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009153,
      name: 'Angel (Warren Worthington III)',
      description: '',
      modified: '2012-05-30T14:06:57-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009153',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1017574,
      name: 'Angela (Aldrif Odinsdottir)',
      description: '',
      modified: '2014-11-17T17:45:37-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1017574',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010674,
      name: 'Anita Blake',
      description: '',
      modified: '2004-04-14T00:00:00-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010674',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009346,
      name: 'Anne Marie Hoag',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009346',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009154,
      name: 'Annihilus',
      description: '',
      modified: '2013-11-20T17:06:36-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009154',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011301,
      name: 'Anole',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011301',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010802,
      name: "Ant-Man (Eric O'Grady)",
      description: '',
      modified: '2014-03-05T13:20:04-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010802',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009155,
      name: 'Ant-Man (Hank Pym)',
      description: '',
      modified: '2021-08-05T15:11:25-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009155',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010801,
      name: 'Ant-Man (Scott Lang)',
      description: '',
      modified: '2017-01-31T11:03:40-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010801',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011208,
      name: 'Anthem',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011208',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009156,
      name: 'Apocalypse',
      description: '',
      modified: '2014-05-28T12:41:41-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009156',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011253,
      name: 'Apocalypse (Ultimate)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011253',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010866,
      name: 'Aqueduct',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010866',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010773,
      name: 'Arachne',
      description: '',
      modified: '2013-10-24T13:07:59-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010773',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1017438,
      name: 'Araña',
      description: '',
      modified: '2016-03-07T14:41:37-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1017438',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009158,
      name: 'Arcade',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009158',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010686,
      name: 'Arcana',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010686',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009159,
      name: 'Archangel',
      description: '',
      modified: '2013-10-18T12:48:24-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009159',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009160,
      name: 'Arclight',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009160',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010784,
      name: 'Ares',
      description: '',
      modified: '2014-04-29T14:50:59-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010784',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011275,
      name: 'Argent',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011275',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011012,
      name: 'Armadillo',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011012',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011298,
      name: 'Armor (Hisako Ichiki)',
      description: '',
      modified: '2012-03-07T17:26:33-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011298',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010827,
      name: 'Armory',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010827',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009740,
      name: 'Arnim Zola',
      description: "The frail, dwarfish Arnim Zola was born in 1930s Switzerland where he became the world's leading biochemist and genetic engineer.",
      modified: '2012-03-20T12:33:28-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009740',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010748,
      name: 'Arsenic',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010748',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009161,
      name: 'Artiee',
      description: '',
      modified: '2011-10-27T09:59:16-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009161',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010718,
      name: 'Asgardian',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010718',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009162,
      name: 'Askew-Tronics',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009162',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010835,
      name: 'Asylum',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010835',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010336,
      name: 'Atlas (Team)',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010336',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011758,
      name: 'Attuma',
      description: 'Attuma was born into the tribe of Homo mermanus who eschewed civilization to live as nomadic barbarians. For some unrecorded reason, Attuma was endowed with strength far surpassing that of his people.',
      modified: '2021-08-27T21:46:12-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011758',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009163,
      name: 'Aurora',
      description: '',
      modified: '2011-05-10T15:56:51-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009163',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009164,
      name: 'Avalanche',
      description: '',
      modified: '2010-11-05T14:30:34-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009164',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009165,
      name: 'Avengers',
      description: "Earth's Mightiest Heroes joined forces to take on threats that were too big for any one hero to tackle. With a roster that has included Captain America, Iron Man, Ant-Man, Hulk, Thor, Wasp and dozens more over the years, the Avengers have come to be regarded as Earth's No. 1 team.",
      modified: '2020-07-21T10:29:09-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009165',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1015239,
      name: 'Avengers (Ultimate)',
      description: '',
      modified: '2012-07-10T19:18:28-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1015239',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011766,
      name: 'Azazel (Mutant)',
      description: 'A mutant from biblical times, Azazel is the ruler of the Neyaphem and claims that the Earth and everything on it belongs to him.',
      modified: '2011-06-09T11:04:52-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011766',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011456,
      name: 'Balder',
      description: '',
      modified: '2021-08-13T00:06:18-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011456',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009168,
      name: 'Banshee',
      description: '',
      modified: '2013-11-01T16:27:08-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009168',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009596,
      name: 'Banshee (Theresa Rourke)',
      description: 'The daughter of former X-Men member Sean Cassidy, a.k.a. Banshee, and Maeve Rourke, Theresa Rourke was raised by her first cousin once removed, mutant terrorist Thomas Cassidy, a.k.a. Black Tom.',
      modified: '2011-03-23T17:37:27-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009596',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011778,
      name: 'Baron Mordo (Karl Mordo)',
      description: 'Born in 1921, Karl Mordo was the son of Nikolai Mordo.  He vowed that, as the second Baron Mordo, he would achieve his father’s hopes and more.',
      modified: '2021-08-12T22:48:49-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011778',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009169,
      name: 'Baron Strucker',
      description: '',
      modified: '2012-03-20T12:30:55-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009169',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009170,
      name: 'Baron Zemo (Heinrich Zemo)',
      description: '',
      modified: '2017-08-24T12:46:19-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009170',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1010906,
      name: 'Baron Zemo (Helmut Zemo)',
      description: '',
      modified: '2011-02-24T13:21:20-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1010906',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011137,
      name: "Baroness S'Bak",
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011137',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011354,
      name: 'Barracuda',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011354',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009550,
      name: 'Bart Rozum',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009550',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009171,
      name: 'Bastion',
      description: '',
      modified: '2013-10-24T13:07:45-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009171',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009172,
      name: 'Batroc the Leaper',
      description: '',
      modified: '2011-03-03T11:45:12-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009172',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009173,
      name: 'Battering Ram',
      description: '',
      modified: '1969-12-31T19:00:00-0500',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009173',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1011785,
      name: 'Battlestar',
      description: 'Lamar Hoskins was once a wrestler who was given superhuman strength by the Power Broker.',
      modified: '2021-08-12T23:47:13-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1011785',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    },
    {
      id: 1009174,
      name: 'Beak',
      description: '',
      modified: '2011-06-01T16:04:59-0400',
      thumbnail: [Object],
      resourceURI: 'http://gateway.marvel.com/v1/public/characters/1009174',
      comics: [Object],
      series: [Object],
      stories: [Object],
      events: [Object],
      urls: [Array]
    }
  ]
} 

const listaDependentes = [...results.results.name]

console.log(listaDependentes)